version: 0.2
phases:
  install:
    runtime-versions:
      php: 7.4
  build:
    commands:
      - echo 'Building PHP application'
      - cp -r ./* $CODEBUILD_SRC_DIR
artifacts:
  files: '**/*'
  base-directory: $CODEBUILD_SRC_DIR
